// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// predprobCpp
double predprobCpp(int y, int n, int nmax, double a, double b, double p0, double theta_t);
RcppExport SEXP ph2bayes_predprobCpp(SEXP ySEXP, SEXP nSEXP, SEXP nmaxSEXP, SEXP aSEXP, SEXP bSEXP, SEXP p0SEXP, SEXP theta_tSEXP) {
  BEGIN_RCPP
  Rcpp::RObject __result;
  Rcpp::RNGScope __rngScope;
  Rcpp::traits::input_parameter< int >::type y(ySEXP);
  Rcpp::traits::input_parameter< int >::type n(nSEXP);
  Rcpp::traits::input_parameter< int >::type nmax(nmaxSEXP);
  Rcpp::traits::input_parameter< double >::type a(aSEXP);
  Rcpp::traits::input_parameter< double >::type b(bSEXP);
  Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
  Rcpp::traits::input_parameter< double >::type theta_t(theta_tSEXP);
  __result = Rcpp::wrap(predprobCpp(y, n, nmax, a, b, p0, theta_t));
  return __result;
  END_RCPP
}
